### ISSUE TITLE
ロゴ募集要項を作成

### ISSUE THREAD

**Issue by horaotoko** [fukuokarb/logo#1]
必要な項目

- 目的
  - なんのためにロゴをリデザインするのか @udzura ？
- 利用用途
- 要望
  - イメージ
  - これまでの課題など
- 応募概要
  - 応募方法
  - 締め切り
- ライセンス
  - https://creativecommons.jp/licenses/
  - ここら辺から...パブリックドメインかどうか

**Comment by udzura** [comment]
ありがとうございます！

> 目的

なんのため、から、経緯を書いていこうかなと思います。
元々あった [ロゴ](https://github.com/fukuokarb/logos/tree/master/images) は僕が福岡に来た時からあり、流れで使って来たのですが

* このロゴを導入した方がそもそも今福岡から出て行ってしまった
* このロゴを作った頃からのFukuoka.rb関係者はもはや世代交代気味
* データが小さい、ベクタデータがない
* ライセンスが曖昧...（作った方がそもそももはや不明）

と行った形で、このまま使い続けるのは微妙なのではないかという話が出ていました。
そこで、現行Fukuoka.rbミートアップも 100 回を超えて来たのを区切りに、 **今のコミュニティのみんなで** 選んで、なおかつ **ライセンスなどの扱いが使いやすい** ようなロゴを新しく決めるのはどうだろう？ということでリデザインを進めたいと思っております。

----

そのほかについてはお待ちを...

**Comment by horaotoko** [comment]
@udzura 
なるほどですね。

もらった情報で仮組みしてみました。

## 目的

Fukuoka.rbは、発足から100回ものミートアップを行ってきました。その間にもコミュニティ内はどんどんと世代交代していき、立ち上げ当初からは随分と雰囲気が変わってきました。

また[現在利用しているロゴ](https://github.com/fukuokarb/logos/tree/master/images)も、つくられてから同じように時間が経ちました。このロゴを採択した人も県外に移住してしまい、作成者も不明のままで、ベクターデータがなかったり、サイズが小さかったり、利用ライセンスが曖昧だったりする問題を解決できずにいました。

そこで、この100回を超えたタイミングで、新しいFukuoka.rbとしてリスタートするためにロゴを見直そうと思います。今のコミュニティのみんなで選んで、用途的にもライセンス的にも使いやすいロゴを決めたいと思っています。

## 利用用途

- Connpassなどイベントページでの画像利用
- Slackなどコミュニケーションツール上でのアイコン利用
- 登壇イベントなどイベントでの印刷利用
- Tシャツなどのグッズ利用

### 要望

- イメージ
- これまでの課題

### 応募概要

- 締め切りは **hoge** までとなっております
- **hoge** までデータを送付してください
- ライセンスは **hoge** で利用する予定です
- 報酬は **hoge** です

**Comment by udzura** [comment]
ちょっと報酬周りで思ったんですが、「こういうことをやります！」という要項を先に出しちゃって、
その上で「スポンサー度として報酬を出してくれる企業さんを募集！」ってしちゃったほうが、話をつけやすいのかもなあと思ったりしました。
なのでまずは拡散できる形にするといいのかな...。

**Comment by horaotoko** [comment]
@udzura 
どちらにせよ要項を早く決めた方がよいかと思うので、
空欄になってるところを決めちゃいましょう。

- 要望
  - 使って欲しい色や形はありますか？
  - 利用用途以外に「こういう風に使いたい」というリクエストはありますか？
- 応募概要
  - 来年の4月のRubyKaigiまでにロゴをお披露目できるとよさそうなので、3月締め切りでどうですか？
  - issue上に、こちらが指定するフォーマットでロゴの画像を掲載してもらう、でやり方はよいですか？
  - 採択後に素材データを送っていただく際の手段、応募者に委ねるでよいですか？（Dropboxとか）
  - 報酬はとりあえず後で

**Comment by udzura** [comment]
新しいロゴは無事決まりました。ありがとうね...
